### ISSUE TITLE
Feature: Proxy copying across LODs

### ISSUE THREAD

**Issue by bloodbine** [MrClock8163/Arma3ObjectBuilder#19]
### Category

Objectbuilder Utilities

### Name of new feature

Proxy copying across LODs

### Description

Name says it all, it gets annoying having to manually redo the proxies over every resolution LOD and would be nice to be able to copy them over.

**Comment by MrClock8163** [comment]
Added the first draft of the function in a recent commit c3f66a5

**Comment by MrClock8163** [comment]
Proxy copying, along with 2 other similar functions is coming in 2.0.0
