### ISSUE TITLE
Change: Validation Tool should consider active Triangulate mods when checking if model is tris

### ISSUE THREAD

**Issue by m0kka** [MrClock8163/Arma3ObjectBuilder#21]
### Feature to change

Validation Side Panel Tool

### Description

The Validation tool should be able to recognize active Triangulate modifiers on a mesh when verifying, whether the geometry currently being validated is properly triangulated.

### Contact details

@Mokka on Discord

**Comment by MrClock8163** [comment]
Need to check if the validation functions could work on the evaludated objects returned by `obj.evaluated_get(bpy.context.evaluated_depsgraph_get())`

**Comment by MrClock8163** [comment]
Update implemented for 2.0.0
