### ISSUE TITLE
Bug: Typo in console log during p3d export

### ISSUE THREAD

**Issue by m0kka** [MrClock8163/Arma3ObjectBuilder#25]
### Add-on version

Release

### Description

There is a typo in the word "vertices" in the console log during p3d export. Really really minor issue.

![](https://i.imgur.com/Bmc3T9r.png)

### Steps to reproduce

- Open a model in Blender with the plugin enabled
- Export a model that contains at least one Arma LOD to p3d
- View the console log

**Comment by MrClock8163** [comment]
I will fix this game breaking issue ASAP @m0kka

**Comment by MrClock8163** [comment]
Fixed
The most important bug of the decade

**Comment by MrClock8163** [comment]
The entire logging has been rewamped withe P3D file handling overhaul, so the issue is EVEN MORE FIXED
