### ISSUE TITLE
Change: Delete Dynamic Rename LOD

### ISSUE THREAD

**Issue by Diablo-1337** [MrClock8163/Arma3ObjectBuilder#36]
### Feature to change

Dynamic LOD Rename

### Description

Hi, why was the automatic name change of the lod removed?

### Contact details

nightmoon.yt228@gmail.com

**Comment by MrClock8163** [comment]
@Diablo-1337 
The dynamic naming was removed from LOD objects because the object names in blender are unique identifiers, and it got really messy as soon as you started to have multiple P3D setups in the same blender file
