### ISSUE TITLE
Feature: Add Geometry 2nd UV sheet validation

### ISSUE THREAD

**Issue by liamcannon** [MrClock8163/Arma3ObjectBuilder#47]
### Category

Import-Export

### Name of new feature

Geometry 2nd UV sheet validation

### Description

When a geometry LOD has 2 uv sheets collision ceases to exist. On export with validation, check for multiple UV sheets on the geometry

**Comment by MrClock8163** [comment]
I'll do some testing, and see if that's actually necessary

**Comment by MrClock8163** [comment]
I did some testing, and weirdly enough, the collision is indeed broken if a 2nd UV set is present, as well as vertex masses. Interestingly, the hit collision remains.
Either way, I won't add it to the validation most likely, but I'll augment the export logic to strip all UV channels from geometry and shadow LODs

**Comment by liamcannon** [comment]
> I did some testing, and weirdly enough, the collision is indeed broken if a 2nd UV set is present, as well as vertex masses. Interestingly, the hit collision remains. Either way, I won't add it to the validation most likely, but I'll augment the export logic to strip all UV channels from geometry and shadow LODs

I brought it up in the wiki channel in a3. I forgot to give them an example last night so it could get added to the geometry LOD wiki

**Comment by MrClock8163** [comment]
Shadows tend to break if you have a texture or material assigned to them, so I'm not sure about that
Why would you UV something if you can't assign a texture to it?

**Comment by MrClock8163** [comment]
As the closing note here
I won't add UVs to the geometry validation, but I made changes to the export logic that remove UV channels on LODs except visual and shadow LODs during the process
