### ISSUE TITLE
Bug: GeometryNode modifier is not applied during export process

### ISSUE THREAD

**Issue by tyen901** [MrClock8163/Arma3ObjectBuilder#49]
### Add-on version

Release

### Description

During export, GeometryNode modifiers are not being applied to the mesh. They are being skipped.

The reason I would like to use Geometry nodes is so that I can do procedural decimation and editing of the meshes to speed up LOD creation.

### Steps to reproduce

1. Create a cube
2. Create a cone
3. Move the cone into a collection named 'NewCollection'
4. Add a Geometry Node modifier to the cube with the following structure ( see image below )
5. Set the input collection to be the NewCollection
6. The cube should now be the cone
7. Check the output p3d file and note that the mesh is not a cone, but a cube
8. Debug the blender addon and note that the apply_modifiers function breaks on the following line https://github.com/MrClock8163/Arma3ObjectBuilder/blob/master/Arma3ObjectBuilder/io/export_p3d.py#L60

![image](https://github.com/MrClock8163/Arma3ObjectBuilder/assets/973390/7238e40d-8296-4efb-b684-185e7fff1a58)

**Comment by MrClock8163** [comment]
Oh yes, Blender and their "everything node" obsession
It's a pity you submitted the issue just after the release
Nonetheless, I'll look into it

**Comment by MrClock8163** [comment]
I did some quick triaging and found the issue
The way the export operates is that it duplicates all LOD objects, sub-objects and proxy objects in the file so it can safely merge them into a singluar object, but it doesn't link them to any scene
It looks like the geometry nodes can't be applied properly if the object is not linked to a scene collection

The issue can be resolved by simply linking the temporary duplicates to the default scene collection during export, but the issue with that is if the export fails for some reason, the temporary files won't be deleted, and they will clutter up the outliner

Maybe I can create a temporary collection, and link the temporary objects to that, then delete them regardless of whether or not the export succeeds
It's worth a shot

**Comment by MrClock8163** [comment]
@tyen901 I implemented a solution
Could you test it on your end?
I will likely put out the release "officially" later this week if the fix is sufficient

[Arma3ObjectBuilder_2_2_1_dev.zip](https://github.com/MrClock8163/Arma3ObjectBuilder/files/14441495/Arma3ObjectBuilder_2_2_1_dev.zip)

**Comment by tyen901** [comment]
It works wonderfully. I'm able to link to a collection and successfully 'instance' it as a geometry node and then export it it.
Thank you for solving this - this will dramatically help improve the workflow for me.

**Comment by MrClock8163** [comment]
Glad to hear it works
But let's keep this issue open until the update is out, so it's more visible for visitors
I'll close it after the patch release
