### ISSUE TITLE
[Bug] Missing length limit on named property names and values

### ISSUE THREAD

**Issue by castelblends** [MrClock8163/Arma3ObjectBuilder#51]
### Add-on version

Release

### Description

Addon version 2.2
Blender version 4.0.2

Hi,

I just installed the addon, tried a model I know it works in Blender 3.6.5, hit export and I get this message

```
raise ValueError("ASCIIZ value is longer (%d + 1) than field length (%d)" % (len(value), field_len))
ValueError: ASCIIZ value is longer (87 + 1) than field length (64)
```
![image](https://github.com/MrClock8163/Arma3ObjectBuilder/assets/61828683/fe995db3-7e09-4f7a-9057-21e6caec1426)

Further investigating this issue, found out it was caused by a named selection string too long:

bisim_named_properties =  "autocenter=0;class=house;map=house;placement=slope;ambientshadowmap=1;placement=slope;sbsource=explicit"

### Steps to reproduce

Install addon
add a cube and set LOD resolution 1
add another cube and set LOD geometry
select geometry lod object
add a new named property called "bisim_named_properties"
set the value to "autocenter=0;class=house;map=house;placement=slope;ambientshadowmap=1;placement=slope;sbsource=explicit"
select both cubes
export with default options plus: 

- Check  select all
- Check validate LODs
- Uncheck warnings as erros

### Stack trace

```shell
P3D export to P:\vbs2\customer\structures\ers_water_meter\ers_water_meter.p3d
        Preprocessing done in 0.026666 sec
        Detected 2 LOD objects
        File type: MLOD
        File version: 257
        Processing LOD data:
        LOD 1
                Name: Resolution 0
                Processing data:
                        Collected vertex normals
                        Collected vertices
                        Collected faces
                        Collected sharp edges
                        Collected UV sets
                        Collected named properties
                        Collected selections
                        Finalized proxy selection names
                File report:
                        Signature: 0
                        Type: P3DM
                        Version: 28.256
                        Vertices: 6449
                        Normals: 9934
                        Faces: 12749
                        Taggs: 7
                Done in 0.242368 sec
        LOD 2
                Name: Geometry
                Processing data:
                        Collected vertex normals
                        Collected vertices
                        Collected faces
                        Collected sharp edges
                        Collected UV sets
                        Collected named properties
                        Collected vertex masses
                        Collected selections
                        Finalized proxy selection names
                File report:
                        Signature: 10000000000000
                        Type: P3DM
                        Version: 28.256
                        Vertices: 40
                        Normals: 45
                        Faces: 60
                        Taggs: 11
                Done in 0.001001 sec
                Forced lowercase
Traceback (most recent call last):
  File "C:\Users\hecas\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Arma3ObjectBuilder\ui\import_export_p3d.py", line 320, in execute
    lod_count, exported_count = export_p3d.write_file(self, context, file)
  File "C:\Users\hecas\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Arma3ObjectBuilder\io\export_p3d.py", line 631, in write_file
    mlod.write(file)
  File "C:\Users\hecas\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Arma3ObjectBuilder\io\data_p3d.py", line 811, in write
    lod.write(file)
  File "C:\Users\hecas\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Arma3ObjectBuilder\io\data_p3d.py", line 559, in write
    tagg.write(file)
  File "C:\Users\hecas\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Arma3ObjectBuilder\io\data_p3d.py", line 250, in write
    self.data.write(file)
  File "C:\Users\hecas\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Arma3ObjectBuilder\io\data_p3d.py", line 82, in write
    binary.write_asciiz_field(file, self.value, 64)
  File "C:\Users\hecas\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Arma3ObjectBuilder\io\binary_handler.py", line 160, in write_asciiz_field
    raise ValueError("ASCIIZ value is longer (%d + 1) than field length (%d)" % (len(value), field_len))
ValueError: ASCIIZ value is longer (70 + 1) than field length (64)
```

### Contact details

hector@castelblends.com

**Comment by MrClock8163** [comment]
That being said, a LOD with such an issue shouldn't even pass the mandatory minimal validation, and should be skipped during export, so it's still a good catch
I'll check out the error, but that still won't allow you to define multiple named properties in one item

**Comment by castelblends** [comment]
Oh!, I see. That explains why after making it into two
bisim_named_properties and splitting the long chain in 3 and 4 properties
it worked. However, this error wasn't showing before using v1.0 and Blender
3.6.5, could it be that the chain was truncated anyways but without
notification?
We are using this addon to make our way from Blender into VBS4 btw and this
is one of many different small things in there.

**Comment by MrClock8163** [comment]
@castelblends Yes indeed
I changed the way this type of data is handled by the binary writer functions in the v2.0.0 release
Prior to that, the data was probably silently truncated
In my opinion it's better for the export to fail, and let the user know that they are not going to get the result they expected, rather than everything going seemingly fine, and then later having a hard time finding where things went south

A v2.2.1 bug fix patch will go out later this week, I set a 63 characters hard limit on the named property names and values in the UI now, so you won't even be able to input a string that is longer than allowed (I forgot to add this limit earlier)

**Comment by MrClock8163** [comment]
Please take note though
This add-on is primarily made for development for Arma 3
The file handling is implemented based on the specifications posted on the BI community wiki, which may or may not be correct and apply for VBS
I have no knowledge of how things work in VBS, or what format differences there might be in the files, so use the plugin with caution

**Comment by castelblends** [comment]
Yeah, I agree with things breaking instead of going quietly under the
table. Thanks.

**Comment by castelblends** [comment]
Yes, I'm aware of that, there are some differences like a missing
underground or wreck LOD but the value of validating geo and res LOD is
priceless and works flawlessly.

**Comment by MrClock8163** [comment]
Then I'm glad you find the plugin useful

As a sidenote, Arma 3 does have wreck LODs, unless you mean something that's actually different in VBS
![kép](https://github.com/MrClock8163/Arma3ObjectBuilder/assets/48679831/9746eaa5-06c4-472f-b5d6-722e46185f62)

**Comment by castelblends** [comment]
my bad, I meant another one... ground layer LOD (not roadway nor land
contact), thanks for the info, help is always well appreciated over here.

**Comment by MrClock8163** [comment]
@castelblends If you can provide a few example P3Ds one-one with each of those missing lods empty, I can try to add support for them
Open a feature request issue if it interests you

**Comment by castelblends** [comment]
That would be great! I'll discuss it with my client and let's see where the
road takes us. Thanks again for your help.

**Comment by MrClock8163** [comment]
I wouldn't need any actual data in such an example P3D
I would only need a P3D that has a single empty LOD of a type that's currently not supported by my addon, so that I can look at the LOD type signature value in the file, and add it to the supported values

**Comment by MrClock8163** [comment]
I also forgot to emphasize
Preparing a model with this addon for export to P3D format requires a very different approach than the VBS4 Model Exchanger setup
Unlike the MEX workflow wich aims to provide a universal interface from different applications through the FBX format to P3D, this addon aims to bring the functionalities of Object Builder (or in the case of VBS4, Oxygen 2) directly into Blender
You don't have to mess with the `bisim_named_properties` and `bisim_named_selections` things, use Vertex Groups and the Named Properties list in the LOD object settings
If you need, I can give you a crash-course on some private channel
