### ISSUE TITLE
[Feature] Very Simple Character Example

### ISSUE THREAD

**Issue by justinstroudbah** [MrClock8163/Arma3ObjectBuilder#66]
### Category

Import-Export

### Description

A basic character animation example. Something very simple, like waving "hello" or even a small calibration. The example would contain:
* The .blend file that originates the character asset
* The resulting RTM and other related output files
* A basic mod config that is only concerned with this example.

I've found that targeted "cookbook-style" examples work well for some, myself included. Something that does away with the clutter and is just a practical implementation of "soldier nodding yes."

The reason I think this is crucial is that the Arma 3 engine has changed drastically over the years (later lip-sync!) and most (if not all) tutorials out there are obsolete. 

Personally, I finally converted a mixamo-named skeleton to Arma 3 and I want to see how I did, but I'm running into various problems with the RTM and an example would sort everything out in short order. I'm hitting things like "animation works, but the scale got screwed up and the character model is so big it's threatening to set my computer on fire."

### Contact details

justinstroud@gmail.com

**Comment by MrClock8163** [comment]
I can understand where you are coming from with your desire for more up to date examples. But how is this a feature request for the addon here?

**Comment by justinstroudbah** [comment]
> I can understand where you are coming from with your desire for more up to date examples. But how is this a feature request for the addon here?

Honestly, the only reason I had it as a feature request is that I figured it would live in this repo, although I could be in error. If  it's not the right place, feel free to remove it (or let me know where I can move it to that makes more sense.)
